networks:
  default:
    name: status
    driver: bridge

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - ./data/uptime-kuma/data:/app/data

  caddy:
    image: caddybuilds/caddy-cloudflare:2.10.0
    restart: always
    environment:
      - CLOUDFLARE_API_TOKEN
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
    cap_add:
      - NET_ADMIN
